### ISSUE TITLE
Dark Squirrel

### ISSUE THREAD

**Issue by Bram91** [microtavor5/PetInfoPlugin#1]
Currently the plugin doesn't support the dark squirrel(metamorphosis of the giant squirrel) this is unlocked by buying the dark acorn in the hallowed sepulchre for 5000 marks.
![image](https://user-images.githubusercontent.com/7499230/85886273-086ddc00-b7e6-11ea-9967-346b3abdf06a.png)

**Comment by microtavor5** [comment]
Thank you for letting me know, I'm adding it right now.

**Comment by microtavor5** [comment]
I added in the pets IDs and it's info. Again thanks for letting me know, I gave you credit in the commits.
