### ISSUE TITLE
Rift guardian variant incorrectly identified

### ISSUE THREAD

**Issue by zdunbrack** [microtavor5/PetInfoPlugin#14]
![image](https://user-images.githubusercontent.com/23144957/135937595-d41af02a-a821-479e-aa90-940960c753c3.png)

I've got a Rift guardian pet that's the blood variant, yet it's identified as the wrath variant (I have 92rc and have never crafted wrath runes). I assume it's just an ID mix-up, but I figured I'd call it out as an issue.

Edit: Somehow my rift guardian was the wrath variant despite me never crafting wrath runes and having it locked since I got it at the blood altar? Not an issue with this plugin, so I can close the issue, but I'm just confused... menagerie bug?

**Comment by microtavor5** [comment]
Weird, but thank you for trying to bring it to my attention, even if it was all sorted in the end!
