### ISSUE TITLE
Rift Guardian wrong variant

### ISSUE THREAD

**Issue by makdid7** [microtavor5/PetInfoPlugin#17]
![image](https://user-images.githubusercontent.com/58991792/145728522-ad97f5dc-4198-4bfc-97bb-4db95660b7bd.png)
Chat: Wrath variant
Real: Fire variant

**Comment by microtavor5** [comment]
Looks like you're right, I'll fix that, and double check the rest of the rift guardian variants to make sure that they all check out

**Comment by microtavor5** [comment]
Ok, updated and checked. The plugin should download the updated list of pets when you restart RuneLite
