### ISSUE TITLE
Ikkle Hydra

### ISSUE THREAD

**Issue by poopsniff44** [microtavor5/PetInfoPlugin#2]
Hydra drop rate is 1/3000, you must have forgot a 0 and put 1/300. :)

![image](https://user-images.githubusercontent.com/67701546/86263737-3ad15d80-bb87-11ea-9ca6-0f69bf640479.png)

**Comment by microtavor5** [comment]
lol, right you are. I just fixed the plugin, and I'm going to submit it to the hub right now.
Thank you for bringing this to my attention :)
