### ISSUE TITLE
[Bug] GOTR Pet "Abyssal Protector" 

### ISSUE THREAD

**Issue by Nick2bad4u** [microtavor5/PetInfoPlugin#21]
There's no drop rate info on how it is obtained with right clicking.
(1 in 4,000)

![image](https://user-images.githubusercontent.com/20943337/221336375-0136f1de-734c-4d3f-80b9-baa8d0b0366c.png)

**Comment by microtavor5** [comment]
Should be updated with the latest version of the pets json
