### ISSUE TITLE
[Request] Add support for Muspah Pet "Muphin"

### ISSUE THREAD

**Issue by Nick2bad4u** [microtavor5/PetInfoPlugin#23]
Currently not supported:
[Muphin ](https://oldschool.runescape.wiki/w/Muphin)- Pet from Boss "[Phantom Muspah](https://oldschool.runescape.wiki/w/Phantom_Muspah)"

**Comment by microtavor5** [comment]
Should be added with the latest version of the pets json. Thank you for your help
