### ISSUE TITLE
Sraracha pet not showing transmog info

### ISSUE THREAD

**Issue by Rowan-Mulder** [microtavor5/PetInfoPlugin#28]
I noticed a orange-legged Sraracha and wondered if this was a transmog, but based on "`The Sraracha is dropped by Sarachnis, at a rate of 1/3000.`" I almost thought the original was modified, just like the Venenatis spiderling.
Would it be possible to have the transmog information added for the Orange and Blue egg sac?

**Comment by microtavor5** [comment]
Sure, I can add more details to the variants.
Sorry I didn't get back to you sooner, things have gotten very busy IRL, so I haven't had time to keep on top of this

**Comment by Rowan-Mulder** [comment]
Thank you! Imo that still was resolved rather quickly. Take care!
