### ISSUE TITLE
Missing Pet Fox (Beaver transmog)

### ISSUE THREAD

**Issue by Michael01011991** [microtavor5/PetInfoPlugin#31]
Hey, I love your plugin. I use it all the time and am constantly checking out peoples pets. I even right click when I know what pet it is just to see who it belongs to. I noticed there were a few of the pets missing, like the beaver transmogs and the quetzin. I think you updated the plugin recently because I noticed the quetzin now works which is great. I really appreciate all the time I'm sure you've put into this plugin and I don't want to sound ungrateful but I think the pet fox is still missing. The Beaver transmog I mean, I think the pet fox and pheasant need to be added, and a nice description on how to get them would be cool too. Thank you for your time

**Comment by microtavor5** [comment]
Hey, sorry I didn't see this, I'll get to adding them now!

**Comment by microtavor5** [comment]
There we go, it should be updated now. Let me know if you have any other thoughts/ideas for the plugin or if you ever see another pet missing it's info.
Thank you for the help, and for enjoying the plugin!

**Comment by Michael01011991** [comment]
Hey thanks for fixing it. Shortly after you sent me those messages I saw
someone with a pet fox in Morytania and I right clicked it and saw that you
fixed it. Looking great thanks for the cool plugin. I'll definitely keep an
eye out for anything else
