### ISSUE TITLE
Typo in info for Red Rocky recolor

### ISSUE THREAD

**Issue by bedmndsn** [microtavor5/PetInfoPlugin#5]
The info says to use Poison Ivy Berries on Rocky, but that is for Tanooki/Ziggy. Red needs Redberries. 
<img width="489" alt="Screen Shot 2020-09-26 at 8 04 13 PM" src="https://user-images.githubusercontent.com/52465600/94354783-8afb7700-0033-11eb-888a-960766e69bb2.png">

**Comment by microtavor5** [comment]
Thank you for letting me know! I'll get to it as soon as I can.

**Comment by microtavor5** [comment]
Alright, updated and submitted for approval
