### ISSUE TITLE
Chaos Ele droprate is wrong

### ISSUE THREAD

**Issue by TaylorAbraham** [microtavor5/PetInfoPlugin#6]
![image](https://user-images.githubusercontent.com/7512973/94839999-c6a49100-03e5-11eb-997f-3842dd67f0f0.png)

This should say 1/300, not 1/33

**Comment by microtavor5** [comment]
Ty for letting me know, I'll try and get on it as soon as I can.

**Comment by microtavor5** [comment]
Alright updated the plugin and submitted to RL.
