### ISSUE TITLE
Sraracha - "/" instead of "." at the end

### ISSUE THREAD

**Issue by makdid7** [microtavor5/PetInfoPlugin#8]
![image](https://user-images.githubusercontent.com/58991792/104944906-95fe5c80-59c0-11eb-832b-f817254419d0.png)

**Comment by microtavor5** [comment]
Sorry for taking so long to get back to you. Thing's have been a little busy. I've fixed it, but will not submit it just yet, I want to do a more thorough look through the file to try and spot out more before I bother the fine folks over at RL with another typo fix

**Comment by microtavor5** [comment]
Sorry it took so long, but the fix is pushed to RL
