### ISSUE TITLE
Little suggestion

### ISSUE THREAD

**Issue by ReinierAarnink1996** [microtavor5/PetInfoPlugin#9]
Hey. Great plugin, nice idea. The only thing I could think of that needs improvement is that it should be together instead of apart: http://prntscr.com/ymsm0n

It makes the menu a bit confusing. This is only with your own pet and another player.

**Comment by microtavor5** [comment]
Sorry for taking so long to get back to you:
I'll look into what I can do, but from what I can tell, it it hard get a specific menu in a specific spot, but I do see why you would like to group the menu items related to your pet together

**Comment by microtavor5** [comment]
Ok looking at the menu-swapper plugin, I think I figured out how to do it

**Comment by microtavor5** [comment]
Sad news: The vanilla client applies a sort to the menu entries before displaying them, but after anything that the plugin does, and there really isn't a lot I can do to get around that.

Unfortunately I have to close the request without being able to have implemented it.
If you have any other ideas to improve the plugin, or see any other existing issues don't hesitate to let me know and I'll try my best to take care of it!
